/**
 * @file Contains abstract key names for keymap.
 * @author DIGITURK\DTHSARI - HAMZA SARI (TECHNOLOGY) <hamza.sari@digiturk.com.tr>
 */

/**
 * Abstract key names.
 */
export const AbstractKeyNames = {
  LEFT: 'LEFT',
  RIGHT: 'RIGHT',
  UP: 'UP',
  DOWN: 'DOWN',
  FCT_1: 'FCT_1',
  FCT_2: 'FCT_2',
  FCT_3: 'FCT_3',
  FCT_4: 'FCT_4',
  PLAY: 'PLAY',
  PAUSE: 'PAUSE',
  PLAY_PAUSE: 'PLAY_PAUSE',
  STOP: 'STOP',
  FORWARD: 'FORWARD',
  REWIND: 'REWIND',
  PREV: 'PREV',
  NEXT: 'NEXT',
  NUM_1: 'NUM_1',
  NUM_2: 'NUM_2',
  NUM_3: 'NUM_3',
  NUM_4: 'NUM_4',
  NUM_5: 'NUM_5',
  NUM_6: 'NUM_6',
  NUM_7: 'NUM_7',
  NUM_8: 'NUM_8',
  NUM_9: 'NUM_9',
  NUM_0: 'NUM_0',
  MUTE: 'MUTE',
  VOL_UP: 'VOL_UP',
  VOL_DOWN: 'VOL_DOWN',
  PROG_UP: 'PROG_UP',
  PROG_DOWN: 'PROG_DOWN',
  INFO: 'INFO',
  HOME: 'HOME',
  SETTINGS: 'SETTINGS',
  VIDEO_SETTINGS: 'VIDEO_SETTINGS',
  AUDIO_SETTINGS: 'AUDIO_SETTINGS',
  MODECHANGE: 'MODECHANGE',
  REC_TIMER: 'REC_TIMER',
  TV_RAD: 'TV_RAD',
  PVR: 'PVR',
  REC: 'REC',
  BACK_SPACE: 'BACK_SPACE',
  BACK: 'BACK',
  OK: 'OK',
  SPECIAL: 'SPECIAL',
  MENU: 'MENU',
  POWER: 'POWER',
  GUIDE: 'GUIDE',
  EXIT: 'EXIT',
  DEL: 'DEL',
  OPTION: 'OPTION',
  PIP: 'PIP',
  VOD: 'VOD',
  HELP: 'HELP',
  AUDIO: 'AUDIO',
  SUBTITLES: 'SUBTITLES',
  FAVORITES: 'FAVORITES',
  SEARCH: 'SEARCH',
  VIEW: 'VIEW',
};
