/**
 * @file Contains keymap definitions for Apple TV device remote.
 * @author DIGITURK\DTHSARI - HAMZA SARI (TECHNOLOGY) <hamza.sari@digiturk.com.tr>
 */

/**
 * Keymap JSON object.
 * Key is abstract name of the pressed key, value is the string of the pressed key from device.
 */
export const KeyMap = {
  // LEFT: '',
  // RIGHT: '',
  // UP: '',
  // DOWN: '',
  // FCT_1: '',
  // FCT_2: '',
  // FCT_3: '',
  // FCT_4: '',
  // PLAY: '',
  // PAUSE: '',
  // PLAY_PAUSE: '',
  // STOP: '',
  // FORWARD: '',
  // REWIND: '',
  // PREV: '',
  // NEXT: '',
  // NUM_1: '',
  // NUM_2: '',
  // NUM_3: '',
  // NUM_4: '',
  // NUM_5: '',
  // NUM_6: '',
  // NUM_7: '',
  // NUM_8: '',
  // NUM_9: '',
  // NUM_0: '',
  // MUTE: '',
  // VOL_UP: '',
  // VOL_DOWN: '',
  // PROG_UP: '',
  // PROG_DOWN: '',
  // INFO: '',
  // HOME: '',
  // SETTINGS: '',
  // VIDEO_SETTINGS: '',
  // AUDIO_SETTINGS: '',
  // MODECHANGE: '',
  // REC_TIMER: '',
  // TV_RAD: '',
  // PVR: '',
  // REC: '',
  // BACK_SPACE: '',
  // BACK: '',
  // OK: '',
  // SPECIAL: '',
  // MENU: '',
  // POWER: '',
  // GUIDE: '',
  // EXIT: '',
  // DEL: '',
  // OPTION: '',
  // PIP: '',
  // VOD: '',
  // HELP: '',
  // AUDIO: '',
  // SUBTITLES: '',
  // FAVORITES: '',
  // SEARCH: '',
  // VIEW: ''
};
